server {
    listen 80;
    server_name _;
    root /app/public;
    client_max_body_size 12m;
    location / { try_files $uri /index.php?$query_string; }
    location = /index.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_pass app:9000;
    }
    location /_protected/ { internal; alias /app/var/assets/; }
    location ~ \.php$ { return 404; }
    location ~ /\. { deny all; }
}
